apiVersion: cert-manager.io/v1

kind: Certificate
metadata:
  name: foodipes-com
spec:
  secretName: foodipes-com-5r2l6 
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - foodipes.com
    - www.foodipes.com

