apiVersion: cert-manager.io/v1

kind: Certificate
metadata:
  name: foodipes-com-tls
spec:
  secretName: foodipes-com-1
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: foodipes.com
  dnsNames:
    - foodipes.com
    - www.foodipes.com

