apiVersion: cert-manager.io/v1

kind: Certificate
metadata:
  name: foodipes-com-tls
spec:
  secretName: foodipes-com 
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - 35.244.58.168
    - www.35.244.58.168

