name: Deploy MultiK8s
on:
  push:
    branches:
      - master
 
env:
  SHA: $(git rev-parse HEAD)
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    permissions:
      contents: 'read'
      id-token: 'write'
 
    steps:
      - uses: actions/checkout@v3
 
      - name: Test
        run: |-
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t easward/react-test -f ./client/Dockerfile.dev ./client
          docker run -e CI=true easward/react-test npm test
 
      - name: Set Identity Provider
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: 'projects/380999466939/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
          service_account: ' git-deployer@multi-k8s-376714.iam.gserviceaccount.com'
          token_format: 'access_token'
      - name: Set Project
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: multi-k8s-376714
 
      - name: Auth
        run: |-
          gcloud --quiet auth configure-docker
 
      - name: Get Credentials
        uses: google-github-actions/get-gke-credentials@v0
        with:
          cluster_name: multi-cluster
          location: us-central1-c
 
      - name: Build
        run: |-
          docker build -t easward/multi-client-10-14:latest -t easward/multi-client-10-14:${{ env.SHA }} -f ./client/Dockerfile ./client
          docker build -t easward/multi-server-10-14:latest -t easward/multi-server-10-14:${{ env.SHA }} -f ./server/Dockerfile ./server
          docker build -t easward/multi-worker-10-14:latest -t easward/multi-worker-10-14:${{ env.SHA }} -f ./worker/Dockerfile ./worker
 
      - name: Push
        run: |-
          docker push easward/multi-client-10-14:latest
          docker push easward/multi-server-10-14:latest
          docker push easward/multi-worker-10-14:latest
 
          docker push easward/multi-client-10-14:${{ env.SHA }}
          docker push easward/multi-server-10-14:${{ env.SHA }}
          docker push easward/multi-worker-10-14:${{ env.SHA }}
 
      - name: Apply
        run: |-
          kubectl apply -f k8s
          kubectl set image deployments/server-deployment server=easward/multi-server-10-14:${{ env.SHA }}
          kubectl set image deployments/client-deployment client=easward/multi-client-10-14:${{ env.SHA }}
          kubectl set image deployments/worker-deployment worker=easward/multi-worker-10-14:${{ env.SHA }}
